name: 'Dependabot vulerabilities notification to Slack'

on:
  schedule:
    - cron: '00 10 1 * *' # Cron Каждый месяц в 10:00

  workflow_dispatch:

jobs:

  Notify-Vulnerabilites:

    runs-on: ubuntu-latest

    steps:
      # Latest version available at: https://github.com/kunalnagarco/action-cve/releases
      - name: Notify Vulnerabilities
        uses: kunalnagarco/action-cve@v1.13.2

        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK2 }}
          severity: medium,high,critical
          count: 30
          ecosystem: npm
