name: 'Dependabot vulerabilities notification to Slack'


on:

  schedule:

    - cron: '45 7 * * *' # Cron 

  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:


jobs:

  Notify-Vulnerabilites:

    runs-on: ubuntu-latest

    steps:

      # Latest version available at: https://github.com/kunalnagarco/action-cve/releases

      - name: Notify Vulnerabilities

        uses: kunalnagarco/action-cve@v1.7.15

        with:

          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # This secret need to be created

          slack_webhook: ${{ secrets.SLACK_WEBHOOK }} # This secret need to be created
